"""Pydantic models mirroring the JSON Schemas in `schemas/`.

The schemas in `schemas/canonical-artifact-v1.json`, `schemas/manifest-v1.json`, and
`schemas/rulepack-v1.json` are the authoritative wire format. The Pydantic models here
mirror them for typed in-process use; CI verifies the two stay in sync (see
`tests/test_schema_sync.py`).

Sprint 1-2 lands the Manifest model end-to-end. Canonical artifact and rulepack models
follow as Sprint 5-7 lands the attribution engine and artifact generator.
"""
from expose.types.canonical import (
    Attribution,
    AttributionTier,
    CanonicalArtifact,
    CloudResource,
    CollectorHealth,
    Delta,
    DeltaAdded,
    DeltaChanged,
    DeltaRemoved,
    Exposure,
    Identifier,
    LeadScore,
    LLMEnrichment,
    OutsideAuthorizedScopeSummary,
    PrimaryIdentifier,
    Provenance,
    QuotaWarning,
    Run as CanonicalRun,
    Target,
    TechStack,
    Tenant as CanonicalTenant,
)
from expose.types.manifest import (
    Manifest,
    ManifestArtifact,
    ManifestSignature,
    ManifestRun,
    ManifestPipeline,
)
from expose.types.rulepack import (
    Action,
    AndCondition,
    AttributionRule,
    LeadScoreFormula,
    LeadScoreModifier,
    LeadScoreWeights,
    NotCondition,
    Outcome,
    OrCondition,
    Predicate,
    PredicateCondition,
    RuleCategory,
    RulePack,
    RulePackDependency,
    TierThresholds,
)
from expose.types.shared import EntityId, RunId, TenantId

__all__ = [
    "Action",
    "AndCondition",
    "Attribution",
    "AttributionRule",
    "AttributionTier",
    "CanonicalArtifact",
    "CanonicalRun",
    "CanonicalTenant",
    "CloudResource",
    "CollectorHealth",
    "Delta",
    "DeltaAdded",
    "DeltaChanged",
    "DeltaRemoved",
    "EntityId",
    "Exposure",
    "Identifier",
    "LLMEnrichment",
    "LeadScore",
    "LeadScoreFormula",
    "LeadScoreModifier",
    "LeadScoreWeights",
    "Manifest",
    "ManifestArtifact",
    "ManifestPipeline",
    "ManifestRun",
    "ManifestSignature",
    "NotCondition",
    "Outcome",
    "OrCondition",
    "OutsideAuthorizedScopeSummary",
    "Predicate",
    "PredicateCondition",
    "PrimaryIdentifier",
    "Provenance",
    "QuotaWarning",
    "RuleCategory",
    "RulePack",
    "RulePackDependency",
    "RunId",
    "Target",
    "TechStack",
    "TenantId",
    "TierThresholds",
]
